// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwOWQ9FruxKVbPSKZyweqs0ejbdc_bGaU',
    appId: '1:6133589505:web:4d153e30c83b04b93b0200',
    messagingSenderId: '6133589505',
    projectId: 'cofi-auth',
    authDomain: 'cofi-auth.firebaseapp.com',
    storageBucket: 'cofi-auth.firebasestorage.app',
    measurementId: 'G-4Q1D469HLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWbHy15t6iZDems7thDeEa8LtV_3vL8Ew',
    appId: '1:6133589505:android:a6d9fba1e2e27de93b0200',
    messagingSenderId: '6133589505',
    projectId: 'cofi-auth',
    storageBucket: 'cofi-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYMHAX3gSVEyFqXqwrdt5_c8ySf8T4kuo',
    appId: '1:6133589505:ios:89ec1246b0f8f1a53b0200',
    messagingSenderId: '6133589505',
    projectId: 'cofi-auth',
    storageBucket: 'cofi-auth.firebasestorage.app',
    iosClientId: '6133589505-u2v2ke3etluvsmr8k5o1bs7uspou5qgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYMHAX3gSVEyFqXqwrdt5_c8ySf8T4kuo',
    appId: '1:6133589505:ios:89ec1246b0f8f1a53b0200',
    messagingSenderId: '6133589505',
    projectId: 'cofi-auth',
    storageBucket: 'cofi-auth.firebasestorage.app',
    iosClientId: '6133589505-u2v2ke3etluvsmr8k5o1bs7uspou5qgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwOWQ9FruxKVbPSKZyweqs0ejbdc_bGaU',
    appId: '1:6133589505:web:4d153e30c83b04b93b0200',
    messagingSenderId: '6133589505',
    projectId: 'cofi-auth',
    authDomain: 'cofi-auth.firebaseapp.com',
    storageBucket: 'cofi-auth.firebasestorage.app',
    measurementId: 'G-4Q1D469HLN',
  );
}
